steps:
  # 1) Instalar dependencias Node
  - name: node:18
    entrypoint: npm
    args: ["install"]

  # 2) Construir EverShop
  - name: node:18
    entrypoint: npm
    args: ["run", "build"]

  # 3 y 4) Instalar Python + ejecutar pruebas Selenium
  - name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r selenium-tests/requirements.txt
        pytest selenium-tests/tests --maxfail=1 --disable-warnings -q

  # 5) Desplegar App Engine
  - name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "app.yaml", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY
